feature/20 Add service worker and online status
chicago-yandex-bulls/client-server-template-with-vite pull request #20
Opened 2022-10-12 10:14 UTC by EkaterinaGulevich

### Добавление Service Worker
Задачи - https://trello.com/c/rLSlDX2e/20 и https://trello.com/c/qpSDgiKG/24

Протестировать продакш сборку с этой задачей можно здесь - https://temppwa-dadec.web.app/

### Скриншоты
![image](https://user-images.githubusercontent.com/104461069/195315974-6b2ed876-5111-4763-83fc-7bf66e4342a5.png)
![image](https://user-images.githubusercontent.com/104461069/195316074-938d02a9-b4b1-4ef8-9c94-f8d125930e60.png)

2022-10-14 15:20 UTC, tmko16 approved these changes

2022-10-15 19:34 UTC, Mr-LYY requested changes
Константы, из которых ты мапишь компоненты вынеси плз в отдельный файл, а остальные коменты не обязательны)

2022-10-15 19:34 UTC, Mr-LYY commented on packages/client/src/components/StartPage/StartPage.tsx
> +  ];
Эти константы нужно вынести из компонента наверх, а лучше в отдельный файл константс. Каждый раз константы создаются заново вместе с компонентами и новые ссылки приводят к ререндерам ненужным.

2022-10-15 19:34 UTC, Mr-LYY commented on packages/client/src/components/StartPage/StartPage.tsx
> +  const gameResult = window.location.hash;
Пока норм, но в будущем, когда добавим SSR, везде где есть window в коде, компонент будет ложиться с ошибкой, потому что в ноде нет виндоу. Решается переносом в юзЭффект или юзЛейаутЭффект, так как они работают только на клиенте. Либо проверкойна виндоу.

2022-10-15 19:34 UTC, Mr-LYY commented on packages/client/src/components/StartPage/StartPage.tsx
> +  };
Методы, которые передаешь как пропсы другим компонентам будут вызывать их ререндер каждый раз при пересоздании. Чтобы сохранить ссылку для чилдренов, нужно обернуть в useCallback.

Тут не достаточно просто тоглера с prevState => !prevState? На твое усмотрение)

2022-10-15 19:34 UTC, Mr-LYY commented on packages/client/src/hooks/useNavigatorOnLine.ts
> +    window.addEventListener('offline', setOffline);
Можно упростить до window.addEventListener('online', setOnline, { once: true });

Но тогда нужны зависимости, потому что после срабатывания обработчика с методом once true, после срабатывания он умрет. Соответственно, если в течении жизни компонента статус изменится несколько раз, то последующие изменения статуса не отработают. Можно не париться и оставить как есть))

2022-10-18 09:17 UTC, EkaterinaGulevich commented on packages/client/src/hooks/useNavigatorOnLine.ts
> +    window.addEventListener('offline', setOffline);
прочитала, про once:true - Это означает, что обработчик вызовется только один раз, но нам нужна подписка на все разы, поэтому оставляем как есть, и на unMount отписываемся

2022-10-18 09:24 UTC, EkaterinaGulevich commented on packages/client/src/components/StartPage/StartPage.tsx
> +  };
fxd на оба коммента

2022-10-18 09:31 UTC, EkaterinaGulevich commented on packages/client/src/components/StartPage/StartPage.tsx
> +  ];
fxd через useMemo

2022-10-18 10:02 UTC, Mr-LYY approved these changes

2022-10-18 10:02 UTC, merged