Feature/7 13
chicago-yandex-bulls/client-server-template-with-vite pull request #21
Opened 2022-10-13 19:38 UTC by Mr-LYY

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-10-14 15:13 UTC, tmko16 approved these changes

2022-10-16 16:02 UTC, EkaterinaGulevich requested changes

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/utils/apiHandler.ts
> +  console.log(reason);
```suggestion
  console.error(reason);
```

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/store/interfaces.ts
> +export type InitialUserType = {
совершенно не критично, но можем договориться называть типы не с постфиксом Type, а с префиксом T, так короче будет

```suggestion
export type TInitialUser = {
```

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/store/constants.ts
> +export const INITIAL_USER = {
Этот файл кажется не нужен

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/components/ProfilePage/ProfilePage.tsx
> +  const { first_name, second_name } = useAppSelector<InitialUserType>(state => state.common.currentUser);
```suggestion
  const { first_name, second_name } = useAppSelector(state => state.common.currentUser);
```

`<InitialUserType>` - это лишнее, так как и так по селектору будет вычислен тип

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/store/commonSlice.ts
> +  isLoading: false,
что-то не очень понятно, на что должен влиять isLoading в common state. Он точно здесь нужен?

просто, как будут этим общим флагом управлять, допустим несколько компонентов или запросов? Не будут ли они пребивать флаг независимо друг от друга.

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/components/EntranceModal/RegistrationForm/RegistrationForm.tsx
> +        name="password"
```suggestion
        name="password"
        type="password"
```

ну и для поля повторить пароль + на странице авторизации

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/components/Header/Header.tsx
> +  const isAuthorized = !!sessionStorage.getItem(IS_AUTHORIZED_KEY);
бэковские куки живут дольше, но мы на фронте сейчас считаем, что пользователь авторизован только в течение сессии. 
Поэтому если пользователь авторизуется, закроет вкладку и откроет ее снова, то фронт станет считать пользователя не авторизованным, при этом запрос на бэк при авторизации будет выдавать ошибку о том, что пользователь все-таки авторизован. И происходит конфликт... Фронт не дает играть, пока не авторизуешь, а бэк не дает авторизоваться, потому что мы еще авторизованы и токен не прогорел.

Так что нужно как-то обработать этот момент. 

Я бы предложила при загрузке страницы делать запрос на гетЮзер. Если он успешный, то записываем данные в стор, если нет, то заставляем пользователя залогиниться. 

Так же предлагаю не завязываться на сессию, так как токен хранится и управляется бэком, а значит только бэк может точно знать, авторизован ли пользователь. 
Если пользователь все-таки принудительно захочет убить токен, то нажмет на кнопку логаут

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/services/api/useAuthApi.ts
> +export type AuthApiSignUp = {
```suggestion
export type TAuthApiSignUp = {
```

типы обычно называют с префиксом `T` либо с постфиксом `Type` (я за `T`)

так читать код удобнее

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/services/api/useAuthApi.ts
> +      body: JSON.stringify(data),
дублируется JSON.stingify

Может перенести эту обработку в useBaseApi ?

2022-10-16 16:02 UTC, EkaterinaGulevich commented on packages/client/src/services/controllers/useAuthController.ts
> +        sessionStorage.setItem(IS_AUTHORIZED_KEY, 'true');
Кстати, в дополнение комментарию выше про сессию. Если пользователь не выйдет из сессии, и вкладка долго будет открыта и не ипользоваться, то токен на бэке так же может прогореть и получим обратную ситуацию, что фронт будет считать пользователя авторизованным (хотя это не так) и даже не даст пользователю авторизоваться. При этом все запросы будут падать с ошибкой unauthorized

2022-10-17 07:47 UTC, Mr-LYY commented on packages/client/src/utils/apiHandler.ts
> +  console.log(reason);
Done

2022-10-17 07:48 UTC, Mr-LYY commented on packages/client/src/store/interfaces.ts
> +export type InitialUserType = {
Done

2022-10-17 07:49 UTC, Mr-LYY commented on packages/client/src/store/constants.ts
> +export const INITIAL_USER = {
Мне приятнее держать константы в отдельных файлах. Если критично, могу вернуть)

2022-10-17 07:49 UTC, Mr-LYY commented on packages/client/src/components/ProfilePage/ProfilePage.tsx
> +  const { first_name, second_name } = useAppSelector<InitialUserType>(state => state.common.currentUser);
Done

2022-10-17 07:54 UTC, Mr-LYY commented on packages/client/src/store/commonSlice.ts
> +  isLoading: false,
Чтобы можно было из разных мест управлять одним универсальным лоадером. Сам лоадер лижит в АПП, его не активировать пропсами, почему плох общий стейт? Можно сделать конекстом или стораджем, но зачем, если есть редакс? Или в чем вопрос?

Так как лоадер общий, на всю страницу, а не локальный, то его нельзя просто юзать в инлайн лоадерах и все. А двух отрендеренных страниц быть не может одновременно

2022-10-17 07:56 UTC, Mr-LYY commented on packages/client/src/components/EntranceModal/RegistrationForm/RegistrationForm.tsx
> +        name="password"
Еще не делал никакой валидации. Хотел оставить это на отдельный таск

2022-10-17 07:57 UTC, Mr-LYY commented on packages/client/src/components/Header/Header.tsx
> +  const isAuthorized = !!sessionStorage.getItem(IS_AUTHORIZED_KEY);
Согласен, исправлю. Я хотел изначально получить время жизни быковской куки и проверять на это в том числе, но этого получить не удалось и оставил локал. Без привязки к куки действительно смысла нет в этом и баг действительно появляется

2022-10-17 07:59 UTC, Mr-LYY commented on packages/client/src/services/api/useAuthApi.ts
> +export type AuthApiSignUp = {
Done

2022-10-17 08:11 UTC, Mr-LYY commented on packages/client/src/services/api/useAuthApi.ts
> +      body: JSON.stringify(data),
Done

2022-10-17 08:20 UTC, Mr-LYY commented on packages/client/src/services/controllers/useAuthController.ts
> +        sessionStorage.setItem(IS_AUTHORIZED_KEY, 'true');
Done

2022-10-17 08:21 UTC, Mr-LYY commented on packages/client/src/components/Header/Header.tsx
> +  const isAuthorized = !!sessionStorage.getItem(IS_AUTHORIZED_KEY);
Done

2022-10-17 15:16 UTC, Mr-LYY commented on packages/client/src/store/commonSlice.ts
> +  isLoading: false,
Проверил, оно итак сделано не тоглером, а значением, так что вообще не вижу с этим проблем)

2022-10-18 08:38 UTC, EkaterinaGulevich approved these changes

2022-10-18 08:41 UTC, merged