feat: Добавлен web api fullscreen api
chicago-yandex-bulls/client-server-template-with-vite pull request #25
Opened 2022-10-26 06:43 UTC by tmko16

### Какую задачу решаем
Добавляет ещё одно WEB API  - Fullscreen API [Ссылка на задачу](https://trello.com/c/zV5cbtgo/37-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D1%82-%D0%B5%D1%89%D1%91-%D0%BE%D0%B4%D0%BD%D0%BE-web-api-%D0%BA%D1%80%D0%BE%D0%BC%D0%B5-canvas-fetch)
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-10-30 20:22 UTC, Mr-LYY commented on packages/client/src/components/GamePage/GamePage.tsx
> +    const gameCanvas = document.querySelector('#game');
Может быть сделать через Ref, чтобы не искать каждый ререндер элемент? Плюс на странице самой игры создается реф для канваса, а если мы его создадим тут, то не нужно будет создавать там. Рефы не влияют на ререндер компонента, в отличие от стейта

2022-10-30 20:22 UTC, Mr-LYY commented on packages/client/src/components/GamePage/GamePage.tsx
> +    const gameCanvas = document.querySelector('#game');
Тогда в Канвас компоненте мы могли бы прокинуть реф через форвард реф и удалить строчку с созданием рефа.

export const CanvasComponent = forwardRef((_, ref) => {

2022-10-31 14:44 UTC, EkaterinaGulevich commented on packages/client/src/components/GamePage/GamePage.tsx
> +    const gameCanvas = document.querySelector('#game');
Да, давайте попробуем

2022-10-31 17:28 UTC, EkaterinaGulevich commented
У меня вообще пропадает курсор при входе в fullscreen режим

2022-10-31 17:30 UTC, EkaterinaGulevich requested changes

2022-10-31 17:30 UTC, EkaterinaGulevich commented on packages/client/src/components/GamePage/GamePage.css
> +.game-page-wrapper {
в нашем проекте все стили хранятся в useStyles файле

2023-01-02 21:38 UTC, closed without merging