Feature/9 41 leaderboard
chicago-yandex-bulls/client-server-template-with-vite pull request #34
Opened 2022-12-06 05:24 UTC by Mr-LYY

### Завершение игры и апи лидерборда

2022-12-06 06:34 UTC, EkaterinaGulevich requested changes
Закоммитились лишние файлы:
- yarn-error.log
- sw/sw.ts (пустой файл, сервис воркеры переехали в папку services
- src/game/CanvasComponent  (пустой файл)

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/App.tsx
> +        <Route path={'/leaderboard'} element={isUserAuthorized ? <LeaderboardPage /> : <NoAuthPage />} />
Супер, что подрефакторил)) 
Думаю еще страницу с лидербордом в будущем можно сделать доступной для неавторизованного пользователя, если апишка будет нашей. И при оффлайн режиме тоже должна быть доступна, а инфу брать из кэша. Но это на будущее, если время будет.

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/canvas/components/SingleGameCanvas/SingleGameCanvas.tsx
> +      navigate('/leaderboard');
Функция onEnd вызовется на unMount, и даже если пользователь не закончил играть, а просто зашел в игру и вышел, то его счет попадет в таблицу рейтинга. Ты так и хотел? Или может быть именно на окончание игры будем отправлять score? в колбэке makeCoundDownClock

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/canvas/components/PreviewAnimationCanvas/PreviewAnimationCanvas.tsx
> +      ctx.fillStyle = '#ffffff';
а ты точно хочешь оставить белый фон?
тень у змеек выглядит чет не очень при белом фоне

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/components/Header/useStyles.ts
> +      color: 'red',
color: 'red' - не работает

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/canvas/components/SingleGameCanvas/SingleGameCanvas.tsx
> +      navigate('/leaderboard');
И если все же решишь оставлять отправку score даже если пользователь не закончил игру, а просто вышел из нее не дождавшись окончания, то нужно убрать принудительную навигацию на лидерборд. Иначе получается бага:
- зайти в одиночный режим
- выйти из него сразу же нажав в шапке на вкладку Main
- Ожидание: попал на Main. Реальность: попал в лидерборд

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/services/redux/queries/leaderboard.api.ts
> +  id: number;
id не отправляется, он точно нужен в этом типе?
Это в запросе на добавление в рейтинг
![image](https://user-images.githubusercontent.com/104461069/205836511-6f36e350-e54f-4c42-b657-581c7697d94a.png)


А это в запросе на получение рейтинга

![image](https://user-images.githubusercontent.com/104461069/205836647-b0f76e3f-8f22-47a4-8cbb-ea1b52a087dd.png)

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/components/LeaderboardPage/types.ts
> +export type TLeaders = Array<TLeaderData>;
TLeaders - нигде не используется

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/components/LeaderboardPage/LeaderboardPage.tsx
> +import LeaderRow from './LeaderRow/LeaderRow';
А здесь забыл импорты подрефакторить)))
дефолтные остались

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/components/LeaderboardPage/LeaderboardPage.tsx
> +            return <LeaderRow key={index} username={username || login} points={points} position={index + 1} />;
key лучше не index, а составную строку из username и login, так как список лидеров изменчивый

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/components/LeaderboardPage/LeaderboardPage.tsx
> +        )}
Супер, что обработал этот случай! :thumbsup:

2022-12-06 06:34 UTC, EkaterinaGulevich commented on packages/client/src/components/LeaderboardPage/LeaderRow/useStyles.ts
> +  leaderRow: {
Я так понимаю, часть стилей ты вынес из packages/client/src/components/LeaderboardPage/useStyles.ts, но в том файле ты не удалил. Сейчас дублируются стили

2022-12-06 06:37 UTC, EkaterinaGulevich commented
Нет экрана для многопользовательского режима, сделано только для одиночного

2022-12-07 05:35 UTC, Mr-LYY commented on packages/client/src/components/LeaderboardPage/LeaderboardPage.tsx
> +import LeaderRow from './LeaderRow/LeaderRow';
Done

2022-12-07 05:35 UTC, Mr-LYY commented on packages/client/src/components/LeaderboardPage/types.ts
> +export type TLeaders = Array<TLeaderData>;
Done

2022-12-07 05:35 UTC, Mr-LYY commented on packages/client/src/services/redux/queries/leaderboard.api.ts
> +  id: number;
Done

2022-12-07 05:36 UTC, Mr-LYY commented on packages/client/src/components/Header/useStyles.ts
> +      color: 'red',
Done

2022-12-07 05:37 UTC, Mr-LYY commented on packages/client/src/canvas/components/PreviewAnimationCanvas/PreviewAnimationCanvas.tsx
> +      ctx.fillStyle = '#ffffff';
В след ПР поменяю на картинку

2022-12-07 05:37 UTC, Mr-LYY commented on packages/client/src/canvas/components/SingleGameCanvas/SingleGameCanvas.tsx
> +      navigate('/leaderboard');
Done для сингл, для многопользовательского проверь плз

2022-12-07 06:55 UTC, EkaterinaGulevich requested changes

2022-12-07 06:55 UTC, EkaterinaGulevich commented on .gitignore
> +yarn-error.log
файл yarn-error.log все равно остался в PR, нужно его просто удалить
а так получается, что в предыдущем коммите ты его добавил, потом добавил в игнор, а дальше пока он в игноре с ним ничего нельзя сделать, ни отредактировать ни удалить)

2022-12-07 06:55 UTC, EkaterinaGulevich commented on packages/client/src/canvas/components/MultiGameCanvas/MultiGameCanvas.tsx
> +    navigate('/leaderboard');
та же история, что и в сингл режиме была. Твою логику нужно вставить туда, где ты удалил консоль логи. В многопользовательском режиме это надо вставить в обработчик события "finished" в сокете

2022-12-07 06:55 UTC, EkaterinaGulevich commented on packages/client/src/components/LeaderboardPage/GameFinalScreen/PlayerRecord/useStyles.ts
> +    backgroundColor: 'rgba(204,198,198,0.63)',
мб цвет из палитры взять?

2022-12-07 06:55 UTC, EkaterinaGulevich commented on packages/client/src/components/LeaderboardPage/LeaderboardPage.tsx
> +import LeaderRow from './LeaderRow/LeaderRow';
not done

2022-12-07 06:55 UTC, EkaterinaGulevich commented on packages/client/src/components/LeaderboardPage/LeaderboardPage.tsx
> +import LeaderRow from './LeaderRow/LeaderRow';
GameFinalScreen и LeaderRow 
и Loader

2022-12-07 06:55 UTC, EkaterinaGulevich commented on packages/client/src/services/redux/types/commonState.ts
> +  lastScore: null | number | IMultiPLayerScore[];
не выглядит хорошим вариантом так типизировать поле lastScore, слишком разные типы.... и null и number и массив объектов...
думаю лучше добавить новое поле lastMultiScore, и всякий раз когда играешь в одиночный режим, очищаешь поле lastMultiScore, и наоборот, когда играешь в многопользовательский, то очищаешь lastScore.

Либо можно сделать вариант, что поле lastScore всегда массив, для одиночного режима там будет только один элемент, а для многопользовательского - много элементов.

Но текущий вариант точно какой-то замороченный. Всякий раз, когда я буду доставать из стора переменную, мне нужно будет проверять, а точно ли она массив, а если нет, то это число или null. Уфф... =))

2022-12-07 06:55 UTC, EkaterinaGulevich commented on packages/server/package.json
> +    "dev": "nodemon index.ts",
ая-я-яй =))
переменная не просто так прокидывается, на нее можно ориентироваться в коде. Нужно вернуть, хитрец))
Поставь cross-env =)

2022-12-07 18:44 UTC, Mr-LYY commented on packages/server/package.json
> +    "dev": "nodemon index.ts",
Ну ладно ладно)

2022-12-07 19:34 UTC, Mr-LYY commented on packages/client/src/services/redux/types/commonState.ts
> +  lastScore: null | number | IMultiPLayerScore[];
Сделал массивом

2022-12-07 19:45 UTC, Mr-LYY commented on packages/client/src/components/LeaderboardPage/GameFinalScreen/PlayerRecord/useStyles.ts
> +    backgroundColor: 'rgba(204,198,198,0.63)',
Мне нравится этот)

2022-12-07 19:49 UTC, Mr-LYY commented on packages/client/src/canvas/components/MultiGameCanvas/MultiGameCanvas.tsx
> +    navigate('/leaderboard');
Перенес

2022-12-07 19:50 UTC, Mr-LYY commented on packages/client/src/components/LeaderboardPage/LeaderRow/useStyles.ts
> +  leaderRow: {
Неправда)

2022-12-07 19:51 UTC, Mr-LYY commented on packages/client/src/components/LeaderboardPage/LeaderboardPage.tsx
> +import LeaderRow from './LeaderRow/LeaderRow';
Точно дан)

2022-12-07 20:23 UTC, EkaterinaGulevich requested changes

2022-12-07 20:23 UTC, EkaterinaGulevich commented on packages/shared/consts/settings.ts
> +export const GAME_DURATION_MS = 6 * 1000;
60 секунд забыл вернуть.
Вообще наверно можно в зависимости от mode, делать либо 60 сек для прода, либо секунд 10 для дева. 
Либо просто вернуть 60 =)

2022-12-07 20:23 UTC, EkaterinaGulevich commented on packages/client/src/canvas/components/SingleGameCanvas/SingleGameCanvas.tsx
> +            },
а почему id и login равны Null ? У нас же есть инфа о пользователе, да и color тоже в одиночном режиме это red

2022-12-08 03:56 UTC, Mr-LYY commented on packages/client/src/canvas/components/SingleGameCanvas/SingleGameCanvas.tsx
> +            },
Они вообще не нужны для одиночного, их можно отсюда просто убрать,но для соблюдения структуры я оставил

2022-12-09 10:04 UTC, EkaterinaGulevich approved these changes

2022-12-09 10:13 UTC, merged